language: dart
sudo: required
dist: xenial
# Solving firefox issue
services:
  - xvfb
dart:
  - stable
  - beta
  - dev
before_script:
  - pub run chrome_travis:init
  - source $(pub run chrome_travis:env_rc)
script: dart tool/travis.dart