language: dart
sudo: required
dist: xenial
# Solving firefox issue
services:
  - xvfb
dart:
  - stable
  - beta
  - dev
before_script:
  - dart pub run chrome_travis:init
  - source $(dart pub run chrome_travis:env_rc)
script: dart tool/travis.dart

cache:
  directories:
    - $HOME/.pub-cache