name: tekartik_browser_utils
version: 0.1.1
dependencies:
  browser: any
  js: any
  tekartik_common_utils:
    git: git://github.com/tekartik/tekartik_common_utils.dart
dev_dependencies:
  dev_test: any
  test: any
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
dependency_overrides:
#  tekartik_common_utils:
#    path: /opt/devx/git/github.com/tekartik/tekartik_common_utils.dart