name: tekartik_browser_utils
version: 0.6.0
description: Browser utils
author: Alexandre Roux <alex@tekartik.com>
homepage: https://github.com/tekartik/browser_utils.dart
environment:
  sdk: '>=2.0.0-dev.63 <2.0.0'
dependencies:
  browser: any
  synchronized: any
  js: any
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.4.6'
dev_dependencies:
  dev_test: any
  test: '>=1.2.0'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
  build_runner: '>=0.9.1'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'
