name: tekartik_browser_utils
version: 0.5.0
description: Browser utils
author: Alexandre Roux <alex@tekartik.com>
homepage: https://github.com/tekartik/browser_utils.dart
environment:
  sdk: '>=1.20.1 <2.0.0'
dependencies:
  browser: any
  synchronized: any
  js: any
  tekartik_common_utils:
    git: git://github.com/tekartik/common_utils.dart
    version: '>=0.4.6'
dev_dependencies:
  dev_test: any
  test: any
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
dependency_overrides:
#  tekartik_common_utils:
#    path: /opt/devx/git/github.com/tekartik/tekartik_common_utils.dart

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc